version: '3'
networks:
  kfk-net:
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"
    networks:
      - kfk-net
    restart: always
  kafka:
    container_name: kafka
    image: kafka:3.3.2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.21.130:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kfk-net
    restart: always
  kafka-map:
    container_name: kafka-map
    image:
      dushixiang/kafka-map:latest
    depends_on:
      - kafka
    ports:
      - "9001:8080"
    volumes:
      - /opk/kafka/kafka-map/data:/usr/local/kafka-map/data
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin
    restart: always
    networks:
      - kfk-net
  elasticsearch:
    image: elasticsearch:7.17.7  # 镜像
    container_name: elk_elasticsearch  # 定义容器名称
    restart: always  # 开机启动，失败也会一直重启
    environment:
      - "cluster.name=elasticsearch" # 设置集群名称为elasticsearch
      - "discovery.type=single-node" # 以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" # 设置使用jvm内存大小
    volumes:
      - /opt/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins # 插件文件挂载
      - /opt/elk/elasticsearch/data:/usr/share/elasticsearch/data # 数据文件挂载
    ports:
      - 9200:9200
    networks:
      - kfk-net
  kibana:
    image: kibana:7.17.7
    container_name: elk_kibana
    restart: always
    depends_on:
      - elasticsearch # kibana在elasticsearch启动之后再启动
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 # 设置访问elasticsearch的地址
      - I18N_LOCALE=zh-CN # kibana中文界面显示
    ports:
      - 5601:5601
    networks:
      - kfk-net
  logstash:
    image: logstash:7.17.7
    container_name: elk_logstash
    restart: always
    volumes:
      - /opt/elk/logstash/config:/usr/share/logstash/pipeline # 挂载logstash的配置文件
    depends_on:
      - elasticsearch # kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es # 可以用es这个域名访问elasticsearch服务
    ports:
      - 5041:5041
    networks:
      - kfk-net
